AWSTemplateFormatVersion: '2010-09-09'
Description: 'DynamoDB table and Lambda function for tracking apartment listings'

Parameters:
  EnvironmentName:
    Description: Environment name (e.g., dev, prod)
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
  
  TableReadCapacity:
    Description: Read capacity units for the table
    Type: Number
    Default: 1
    MinValue: 1
  
  TableWriteCapacity:
    Description: Write capacity units for the table
    Type: Number
    Default: 1
    MinValue: 1

  SenderEmail:
    Description: Verified SES email address for sending notifications
    Type: String

  RecipientEmail:
    Description: Email address to receive notifications
    Type: String

  ImageUri: 
    Type: String
    Description: URI of the container image

  UpdateTimestamp:
    Type: String
    Description: Timestamp to force update

  ECRRepositoryName:
    Type: String
    Description: Name of the ECR repository
    Default: apartment-tracker

Resources:
  ApartmentListingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'ApartmentListings-${EnvironmentName}'
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref TableReadCapacity
        WriteCapacityUnits: !Ref TableWriteCapacity
      AttributeDefinitions:
        - AttributeName: apartment_id
          AttributeType: S
      KeySchema:
        - AttributeName: apartment_id
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: ApartmentTracker

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Scan
                  - dynamodb:Query
                Resource: !GetAtt ApartmentListingsTable.Arn
        - PolicyName: SESAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ses:SendRawEmail
                  - ses:SendEmail
                Resource: '*'
        - PolicyName: ECRAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:BatchCheckLayerAvailability
                Resource: !Sub 'arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/${ECRRepositoryName}'

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: "Apartment tracker running daily at 9:05 AM Eastern Time (adjusts for DST)"
      FunctionName: !Sub 'apartment-tracker-${EnvironmentName}'
      Role: !GetAtt LambdaExecutionRole.Arn
      PackageType: Image
      Code:
        ImageUri: !Ref ImageUri
      Timeout: 300
      MemorySize: 512
      Environment:
        Variables:
          ENVIRONMENT: !Ref EnvironmentName
          DYNAMODB_TABLE: !Ref ApartmentListingsTable
          SENDER_EMAIL: !Ref SenderEmail
          RECIPIENT_EMAIL: !Ref RecipientEmail
          MIN_SQFT: '650'
      Tags:
        - Key: UpdateTimestamp
          Value: !Ref UpdateTimestamp

  LambdaScheduleRuleEST:
    Type: AWS::Events::Rule
    Properties:
      Description: "Schedule for running apartment tracker at 9:05 AM Eastern Standard Time (Nov-Mar)"
      ScheduleExpression: "cron(5 14 * 11-12,1-3 ? *)"  # 14:05 UTC = 9:05 AM EST
      State: ENABLED
      Targets:
        - Arn: !GetAtt LambdaFunction.Arn
          Id: "ApartmentTrackerScheduleEST"

  LambdaScheduleRuleEDT:
    Type: AWS::Events::Rule
    Properties:
      Description: "Schedule for running apartment tracker at 9:05 AM Eastern Daylight Time (Mar-Nov)"
      ScheduleExpression: "cron(5 13 * 3-11 ? *)"  # 13:05 UTC = 9:05 AM EDT
      State: ENABLED
      Targets:
        - Arn: !GetAtt LambdaFunction.Arn
          Id: "ApartmentTrackerScheduleEDT"

  LambdaSchedulePermissionEST:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunction
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt LambdaScheduleRuleEST.Arn

  LambdaSchedulePermissionEDT:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunction
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt LambdaScheduleRuleEDT.Arn

Outputs:
  TableName:
    Description: Name of the created DynamoDB table
    Value: !Ref ApartmentListingsTable
    Export:
      Name: !Sub '${AWS::StackName}-TableName'
  
  TableArn:
    Description: ARN of the created DynamoDB table
    Value: !GetAtt ApartmentListingsTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-TableArn'
  
  LambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt LambdaFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-LambdaArn'